from __future__ import annotations

import argparse
import csv
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from cable_analyser.analysis import CableAnalysis
from cable_analyser.config_loader import dump_config, load_config
from cable_analyser.geometry import CableGeometry
from cable_analyser.wind_forces import _linear_extrapolate, _load_coefficient_table


VALIDATION_ROOT = ROOT / "output" / "workflow_validation" / "matlab_python_force3_baseline"
PY_DIR = VALIDATION_ROOT / "python"
MAT_DIR = VALIDATION_ROOT / "matlab"
MAT_WORK = MAT_DIR / "workspace"
POST_DIR = VALIDATION_ROOT / "comparison"
CASE_CONFIG = VALIDATION_ROOT / "validation_config_python.yaml"

MONITORS = [
    ("quarter_1", "1/4 span", 26),
    ("midspan", "Midspan", 51),
    ("quarter_3", "3/4 span", 76),
]


def as_posix(path: Path) -> str:
    return str(path.resolve()).replace("\\", "/")


def prepare_python_config(npt: int = 4096) -> Path:
    cfg = load_config(ROOT / "config" / "timur_baseline.yaml")
    cfg["time_history"]["npt"] = npt
    cfg["time_history"]["folder_1"] = ["FORCE_3"]
    cfg["time_history"]["folder_2"] = ["SIM1"]
    cfg["wind_generation"]["enabled"] = False
    cfg["paths"]["output_dir"] = as_posix(PY_DIR)
    cfg["paths"]["save_prefix"] = "PY_FORCE3_BASELINE"
    cfg["solver"]["opensees_path"] = as_posix(Path(cfg["solver"]["opensees_path"]))
    cfg["solver"]["input_tcl"] = as_posix(PY_DIR / "Input.tcl")
    cfg["solver"]["work_dir"] = as_posix(ROOT)
    cfg["display"]["plotter"] = False
    cfg["display"]["modal_plotter"] = False
    cfg["display"]["realtime_monitor"] = False
    CASE_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    dump_config(cfg, CASE_CONFIG)
    return CASE_CONFIG


def write_matlab_runner(npt: int = 4096) -> None:
    MAT_WORK.mkdir(parents=True, exist_ok=True)
    (MAT_WORK / "Output").mkdir(exist_ok=True)
    (MAT_WORK / "tcl_procedures").mkdir(exist_ok=True)
    (MAT_WORK / "data" / "aero_coeffs").mkdir(parents=True, exist_ok=True)

    for name in ["PROCEDURE_OLD.tcl", "PROCEDURE_Raf_6dof.tcl"]:
        shutil.copy2(ROOT / "TIMUR4" / name, MAT_WORK / name)
    for name in ["readColumnFromFile.tcl", "interpolate.tcl", "Wind_velocity_reader.tcl", "Damping_shifter.tcl", "dynamic2.tcl"]:
        shutil.copy2(ROOT / "tcl_procedures" / name, MAT_WORK / "tcl_procedures" / name)
    for name in ["C_D_data.txt", "C_L_data2.txt", "dC_L.txt", "time.txt"]:
        shutil.copy2(ROOT / "data" / "aero_coeffs" / name, MAT_WORK / "data" / "aero_coeffs" / name)

    shutil.copy2(ROOT / "TIMUR4" / "MODAL.m", MAT_WORK / "MODAL.m")

    run_m = f"""%% MATLAB validation runner generated by tools/build_matlab_python_validation.py
clear all; clc;
cd('{as_posix(MAT_WORK)}');
g = 9.80665;
Plotter = 0;
Modal_plotter = 0;
Geometry = 2;
L = 322.8;
Sag = 10.48;
Discretisation = 3.228;
Dia = 0.02862;
Area = pi * Dia^2 / 4;
In = pi * Dia^4 / 64;
Io = 2 * In;
ro2 = Io/Area;
self_weight = 15.9;
E = 69000000000;
G = 4265000000;
ANALYSIS_TYPE = 'TH';
FIBER_SECTION = 1;
TH_path = '{as_posix(ROOT / "data" / "forces" / "FORCE_3" / "SIM1")}';
wind_time_file_validation = '{as_posix(ROOT / "data" / "aero_coeffs" / "time.txt")}';
wind_data_dir_validation = '{as_posix(ROOT / "data" / "forces" / "FORCE_3" / "SIM1")}';
DT = 0.05;
NPt = {npt};
Duration = NPt * DT;
Damping_model = 'Rayleigh';
Modes_to_consider_for_damping = 10;
xi = 0.01;
Pretention_load = 19785.0;
Multiplier_vertical_load = 1.0;
Multiplier_mass = 1.0;
Numbers_of_step_gravity_analysis = 10;
Tollerance = 1e-3;
Number_of_modes_to_consider = 3;

%% Use exact catenary matching Python CableGeometry(type=2)
x = 0:Discretisation:L;
y = zeros(size(x));
low = 1e-6;
high = max(L^2/(8*Sag), L);
while high * (cosh(L/(2*high)) - 1) > Sag
    high = high * 2;
end
low = high / 2;
while low * (cosh(L/(2*low)) - 1) < Sag
    low = low / 2;
end
for iter = 1:100
    mid = (low + high) / 2;
    sag_mid = mid * (cosh(L/(2*mid)) - 1);
    if sag_mid > Sag
        low = mid;
    else
        high = mid;
    end
end
a_cat = (low + high) / 2;
x1 = x - L/2;
z1 = a_cat * cosh(x1 ./ a_cat);
z = z1 - max(z1);
angle = zeros(length(x)-1,1);
for i=1:length(x)-1
    angle(i) = atan((z(i+1)-z(i))/(x(i+1)-x(i)));
end

MODAL
TH_Constant_validation
save('{as_posix(MAT_DIR / "matlab_workspace_variables.mat")}', 'x', 'y', 'z', 'angle', 'DX', 'MN', 'MNT', 'f1', 'a_cat');
"""
    (MAT_WORK / "run_matlab_validation.m").write_text(run_m, encoding="utf-8")

    th = (ROOT / "TIMUR4" / "TH_Constant.m").read_text(encoding="utf-8", errors="ignore")
    th = th.replace("fprintf(fid,'source Wind_velocity_reader.tcl\\n');", "\n".join([
        "fprintf(fid,'set wind_time_file \"{0}\"\\n');".format(as_posix(ROOT / "data" / "aero_coeffs" / "time.txt")),
        "fprintf(fid,'set wind_data_dir \"{0}\"\\n');".format(as_posix(ROOT / "data" / "forces" / "FORCE_3" / "SIM1")),
        "fprintf(fid,'source tcl_procedures/Wind_velocity_reader.tcl\\n');",
    ]))
    th = th.replace("fprintf(fid,'source Damping_shifter.tcl\\n');", "fprintf(fid,'source tcl_procedures/Damping_shifter.tcl\\n');")
    th = th.replace("fprintf(fid,'source dynamic2.tcl\\n');", "fprintf(fid,'source tcl_procedures/dynamic2.tcl\\n');")
    th = th.replace(
        "fprintf(fid,'recorder Node -file Output/Dynamic.out -nodeRange %u %u -dof 1 2 3 disp; \\n',1, length(DX));",
        "fprintf(fid,'recorder Node -file Output/Dynamic.out -time -nodeRange %u %u -dof 1 2 3 disp; \\n',1, length(DX));",
    )
    th = th.replace(
        "fprintf(fid,'recorder Node -file Output/Reaction.out -node 1 -dof 1 2 3 reaction; \\n');",
        "fprintf(fid,'recorder Node -file Output/Reaction.out -time -node 1 -dof 1 2 3 reaction; \\n');",
    )
    th = th.replace("fprintf(fid,'source PROCEDURE_OLD.tcl; \\n');", "fprintf(fid,'source PROCEDURE_OLD.tcl; \\n');")
    th = th.replace("! \"D:\\Pyprogramme\\OpenSees3.8.0\\bin\\OpenSees.exe\" input.tcl", "! \"D:\\Pyprogramme\\OpenSees3.8.0\\bin\\OpenSees.exe\" Input.tcl")
    th = th.replace(
        "fprintf(fid,'set omegaN %f\\n',2*pi*f1);",
        "fprintf(fid,'set omegaN %f\\n',2*pi*f1);\nfprintf(fid,'set xi_structural %f\\n',xi);",
        1,
    )
    (MAT_WORK / "TH_Constant_validation.m").write_text(th, encoding="utf-8")


def run_python_case() -> None:
    PY_DIR.mkdir(parents=True, exist_ok=True)
    cfg_path = prepare_python_config()
    CableAnalysis(str(cfg_path)).run()


def run_matlab_case(matlab_exe: str) -> None:
    write_matlab_runner()
    cmd = [matlab_exe, "-batch", f"run('{as_posix(MAT_WORK / 'run_matlab_validation.m')}')"]
    result = subprocess.run(cmd, cwd=MAT_WORK, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"MATLAB validation failed with exit code {result.returncode}")


def load_dynamic(output_dir: Path, n_nodes: int) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    data = np.loadtxt(output_dir / "Dynamic.out")
    if data.ndim == 1:
        data = data[np.newaxis, :]
    if data.shape[1] == 3 * n_nodes + 1:
        time = data[:, 0]
        arr = data[:, 1:]
    else:
        time = np.arange(data.shape[0]) * 0.05
        arr = data
    return time, arr[:, 0::3], arr[:, 1::3], arr[:, 2::3]


def load_velocity(output_dir: Path, n_nodes: int) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray] | None:
    path = output_dir / "Velocity.out"
    if not path.exists():
        return None
    data = np.loadtxt(path)
    if data.ndim == 1:
        data = data[np.newaxis, :]
    if data.shape[1] == 3 * n_nodes + 1:
        time = data[:, 0]
        arr = data[:, 1:]
    else:
        time = np.arange(data.shape[0]) * 0.05
        arr = data
    return time, arr[:, 0::3], arr[:, 1::3], arr[:, 2::3]


def read_vec(path: Path, n: int | None = None) -> np.ndarray:
    values = np.loadtxt(path)
    return values[:n] if n is not None else values


def damping_by_monitor(output_dir: Path) -> tuple[np.ndarray, dict[str, np.ndarray]]:
    path = output_dir / "damping_change_log.txt"
    if not path.exists():
        return np.array([]), {label: np.array([]) for label, _, _ in MONITORS}
    data = np.loadtxt(path)
    if data.ndim == 1:
        data = data[np.newaxis, :]
    times = np.unique(np.round(data[:, 0], 8))
    result: dict[str, np.ndarray] = {}
    for label, _, node_id in MONITORS:
        idx = node_id - 1
        elems = []
        if idx > 0:
            elems.append(idx)
        if idx < 100:
            elems.append(idx + 1)
        values = np.full(len(times), np.nan)
        for i, t in enumerate(times):
            mask = (np.round(data[:, 0], 8) == t) & np.isin(data[:, 1].astype(int), elems)
            if np.any(mask):
                values[i] = np.mean(data[mask, 3])
        result[label] = values
    return times, result


def coeff_histories(n_steps: int) -> tuple[np.ndarray, dict[str, np.ndarray], dict[str, np.ndarray], dict[str, np.ndarray]]:
    time = read_vec(ROOT / "data" / "aero_coeffs" / "time.txt", n_steps)
    cd_table = _load_coefficient_table(ROOT / "data" / "aero_coeffs" / "C_D_data.txt")
    cl_table = _load_coefficient_table(ROOT / "data" / "aero_coeffs" / "C_L_data2.txt")
    dcl = np.loadtxt(ROOT / "data" / "aero_coeffs" / "dC_L.txt")
    cd: dict[str, np.ndarray] = {}
    cl: dict[str, np.ndarray] = {}
    delta: dict[str, np.ndarray] = {}
    for label, _, node_id in MONITORS:
        u = read_vec(ROOT / "data" / "forces" / "FORCE_3" / "SIM1" / f"NODE_{node_id}_wind_H.txt", n_steps)
        w = read_vec(ROOT / "data" / "forces" / "FORCE_3" / "SIM1" / f"NODE_{node_id}_wind_V.txt", n_steps)
        alpha = np.abs(np.rad2deg(np.arctan2(w, u)))
        cd[label] = _linear_extrapolate(alpha, cd_table[:, 0], cd_table[:, 1])
        cl[label] = _linear_extrapolate(alpha, cl_table[:, 0], cl_table[:, 1])
        delta[label] = cd[label] + _linear_extrapolate(alpha, cd_table[:, 0], dcl) * 180.0 / math.pi
    return time, cd, cl, delta


def export_timeseries(source: str, output_dir: Path, out_dir: Path) -> dict[str, Any]:
    cfg = load_config(CASE_CONFIG)
    geo = CableGeometry(cfg).generate()
    n_nodes = len(geo["x"])
    time, dx, dy, dz = load_dynamic(output_dir, n_nodes)
    n = len(time)
    coeff_time, cd, cl, delta = coeff_histories(min(n, 4096))
    damp_t, damp = damping_by_monitor(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    fields = ["time_s"]
    for label, _, node_id in MONITORS:
        fields.extend([f"{label}_disp_x_m", f"{label}_disp_z_m"])
    for i, t in enumerate(time):
        row: dict[str, Any] = {"time_s": float(t)}
        for label, _, node_id in MONITORS:
            idx = node_id - 1
            row[f"{label}_disp_x_m"] = float(dy[i, idx])
            row[f"{label}_disp_z_m"] = float(dz[i, idx])
        rows.append(row)
    write_csv(out_dir / "three_point_displacement.csv", rows, fields)

    crows: list[dict[str, Any]] = []
    cfields = ["time_s"]
    for label, _, _ in MONITORS:
        cfields.extend([f"{label}_C_D", f"{label}_C_L", f"{label}_delta_D"])
    for i, t in enumerate(coeff_time):
        row = {"time_s": float(t)}
        for label, _, _ in MONITORS:
            row[f"{label}_C_D"] = float(cd[label][i])
            row[f"{label}_C_L"] = float(cl[label][i])
            row[f"{label}_delta_D"] = float(delta[label][i])
        crows.append(row)
    write_csv(out_dir / "three_point_aero_coeff_delta.csv", crows, cfields)

    drows: list[dict[str, Any]] = []
    dfields = ["time_s"] + [f"{label}_xi_mean" for label, _, _ in MONITORS]
    for i, t in enumerate(damp_t):
        row = {"time_s": float(t)}
        for label, _, _ in MONITORS:
            row[f"{label}_xi_mean"] = None if np.isnan(damp[label][i]) else float(damp[label][i])
        drows.append(row)
    write_csv(out_dir / "three_point_damping.csv", drows, dfields)

    summary = {
        "source": source,
        "rows_dynamic": n,
        "time_start": float(time[0]),
        "time_end": float(time[-1]),
        "has_velocity": (output_dir / "Velocity.out").exists(),
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return {"time": time, "disp_y": dy, "disp_z": dz, "cd": cd, "cl": cl, "delta": delta, "damp_t": damp_t, "damp": damp, "geo": geo}


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def quad_timeseries_plot(path: Path, title: str, time: np.ndarray, series: dict[str, np.ndarray], ylabel: str) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(13.5, 8.2), dpi=170, sharex=False)
    axes = axes.ravel()
    colors = {"quarter_1": "#2E74B5", "midspan": "#4A8F5A", "quarter_3": "#C7832B"}
    names = {"quarter_1": "1/4 span", "midspan": "Midspan", "quarter_3": "3/4 span"}
    for label in ["quarter_1", "midspan", "quarter_3"]:
        axes[0].plot(time[: len(series[label])], series[label], lw=1.05, label=names[label], color=colors[label])
    axes[0].set_title("Three-point comparison")
    axes[0].legend(fontsize=8)
    for ax, label in zip(axes[1:], ["quarter_1", "midspan", "quarter_3"]):
        ax.plot(time[: len(series[label])], series[label], lw=1.05, color=colors[label])
        ax.set_title(names[label])
    for ax in axes:
        ax.grid(True, color="#D8DEE8", lw=0.6)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(ylabel)
    fig.suptitle(title, fontsize=15, weight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(path)
    plt.close(fig)


def trajectory_plot(path: Path, data: dict[str, Any], title: str, max_points: int = 2200) -> None:
    time = data["time"]
    dy = data["disp_y"]
    dz = data["disp_z"]
    if len(time) > max_points:
        idxs = np.linspace(0, len(time) - 1, max_points).astype(int)
    else:
        idxs = np.arange(len(time))
    fig, axes = plt.subplots(1, 3, figsize=(16.2, 4.9), dpi=170, layout="constrained")
    for ax, (_, name, node_id) in zip(axes, MONITORS):
        idx = node_id - 1
        sc = ax.scatter(dy[idxs, idx], dz[idxs, idx], c=time[idxs], s=5, cmap="viridis", alpha=0.85)
        ax.plot(dy[idxs, idx], dz[idxs, idx], color="#1E252D", lw=0.35, alpha=0.45)
        ax.set_title(f"{name} (Node {node_id})")
        ax.set_xlabel("x/y horizontal disp (m)")
        ax.set_ylabel("z vertical disp (m)")
        ax.grid(True, color="#D8DEE8", lw=0.6)
        ax.axis("equal")
    fig.colorbar(sc, ax=axes.tolist(), label="Time (s)", shrink=0.86, pad=0.02)
    fig.suptitle(title, fontsize=15, weight="bold")
    fig.savefig(path)
    plt.close(fig)


def write_validation_report(compare_rows: list[dict[str, Any]], py: dict[str, Any], mat: dict[str, Any]) -> None:
    lines = [
        "# MATLAB-Python workflow validation: FORCE_3/SIM1 baseline",
        "",
        "## Purpose",
        "",
        "This validation run compares the active Python/OpenSees workflow with a matched MATLAB/OpenSees validation copy derived from the original Timur project. The run is intended to check parameter wiring, force-file usage, recorder timing, aerodynamic damping, and the three key monitoring points before further galloping interpretation.",
        "",
        "## Matched case",
        "",
        "- Geometry: L = 322.8 m, H/sag = 10.48 m.",
        "- Monitoring nodes: 1/4 span Node 26, midspan Node 51, 3/4 span Node 76.",
        "- Wind/force input: `data/forces/FORCE_3/SIM1`, npt = 4096, dt = 0.05 s.",
        "- Aerodynamic tables: `data/aero_coeffs/C_D.txt`, `C_L.txt`, and `dC_L.txt`.",
        "- Den Hartog discriminator: `delta_D = C_D + dC_L/dalpha`, with the stored derivative converted from per degree to per radian.",
        "",
        "## MATLAB validation-copy corrections",
        "",
        "The original MATLAB project is not directly used as-is for a one-to-one comparison because several defaults differ from the active Python baseline. The validation copy applies only parity corrections:",
        "",
        "- Uses the same `FORCE_3/SIM1` force files instead of an unmatched test folder.",
        "- Uses the same exact catenary geometry expression as the Python `CableGeometry(type=2)` workflow.",
        "- Uses the current corrected `Damping_shifter.tcl`, including per-degree to per-radian conversion and configured structural damping.",
        "- Adds `-time` to dynamic and reaction recorders so adaptive OpenSees steps are compared by physical time rather than row number.",
        "",
        "## Run completion",
        "",
        f"- Python dynamic output: {len(py['time'])} rows, {float(py['time'][0]):.3f}-{float(py['time'][-1]):.3f} s.",
        f"- MATLAB dynamic output: {len(mat['time'])} rows, {float(mat['time'][0]):.3f}-{float(mat['time'][-1]):.3f} s.",
        "",
        "Both runs enter a severe large-response/nonlinear regime before the requested 204.8 s record ends. Python stops at about 160.135 s, while the MATLAB validation copy continues farther to about 186.388 s. This is treated as a non-normal solver/instability outcome, not as a completed smooth response record.",
        "",
        "## Three-point displacement comparison",
        "",
        "| Monitor | Node | common end (s) | RMS x/y diff, common (m) | RMS z diff, common (m) | RMS x/y diff, 0-120s (m) | RMS z diff, 0-120s (m) |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in compare_rows:
        lines.append(
            f"| {row['monitor']} | {row['node']} | {row['common_time_end_s']:.3f} | "
            f"{row['rms_diff_x_common']:.6g} | {row['rms_diff_z_common']:.6g} | "
            f"{row['rms_diff_x_0_120s']:.6g} | {row['rms_diff_z_0_120s']:.6g} |"
        )
    lines.extend([
        "",
        "## Interpretation",
        "",
        "The early and moderate-response interval, especially 0-120 s, shows very close agreement between MATLAB and Python, with displacement RMS differences below 0.001 m at all three monitoring points. This strongly supports that geometry, force-file scaling, aerodynamic coefficient lookup, damping formulation, and recorder timing are matched.",
        "",
        "The larger differences over the full common interval occur after the response grows rapidly. In this regime the analysis is sensitive to nonlinear solution path, adaptive time stepping, and convergence handling. The divergence therefore flags a production-workflow requirement: failed or non-normal simulations must be recorded explicitly and interpreted together with coverage metrics, rather than being silently treated as complete time histories.",
        "",
        "## Output package",
        "",
        f"- Python outputs: `{PY_DIR / 'three_point_outputs'}`",
        f"- MATLAB outputs: `{MAT_DIR / 'three_point_outputs'}`",
        f"- Comparison CSV: `{POST_DIR / 'python_matlab_three_point_comparison.csv'}`",
        "",
        "Each side contains four-panel plots for horizontal displacement, vertical displacement, C_D, C_L, Den Hartog `delta_D`, effective damping, plus x-z trajectory plots for the three monitoring points.",
        "",
    ])
    (POST_DIR / "workflow_validation_report.md").write_text("\n".join(lines), encoding="utf-8")


def postprocess() -> None:
    POST_DIR.mkdir(parents=True, exist_ok=True)
    py = export_timeseries("python", PY_DIR, PY_DIR / "three_point_outputs")
    mat_output = MAT_WORK / "Output"
    mat = export_timeseries("matlab", mat_output, MAT_DIR / "three_point_outputs")

    for source, data, out in [("python", py, PY_DIR), ("matlab", mat, MAT_DIR)]:
        t = data["time"]
        quad_timeseries_plot(out / "three_point_outputs" / "disp_x_quad.png", f"{source}: horizontal displacement", t, {l: data["disp_y"][:, node - 1] for l, _, node in MONITORS}, "disp x/y (m)")
        quad_timeseries_plot(out / "three_point_outputs" / "disp_z_quad.png", f"{source}: vertical displacement", t, {l: data["disp_z"][:, node - 1] for l, _, node in MONITORS}, "disp z (m)")
        coeff_t, _, _, _ = coeff_histories(4096)
        quad_timeseries_plot(out / "three_point_outputs" / "cd_quad.png", f"{source}: C_D", coeff_t, data["cd"], "C_D")
        quad_timeseries_plot(out / "three_point_outputs" / "cl_quad.png", f"{source}: C_L", coeff_t, data["cl"], "C_L")
        quad_timeseries_plot(out / "three_point_outputs" / "delta_d_quad.png", f"{source}: Den Hartog delta_D", coeff_t, data["delta"], "delta_D")
        if len(data["damp_t"]):
            quad_timeseries_plot(out / "three_point_outputs" / "damping_quad.png", f"{source}: effective damping", data["damp_t"], data["damp"], "xi_total")
        trajectory_plot(out / "three_point_outputs" / "xz_trajectory.png", data, f"{source}: x-z displacement trajectory")

    compare_rows = []
    for label, name, node_id in MONITORS:
        idx = node_id - 1
        t_end = min(float(py["time"][-1]), float(mat["time"][-1]))
        common_t = np.arange(max(float(py["time"][0]), float(mat["time"][0])), t_end + 1e-9, 0.05)
        py_x = np.interp(common_t, py["time"], py["disp_y"][:, idx])
        py_z = np.interp(common_t, py["time"], py["disp_z"][:, idx])
        mat_x = np.interp(common_t, mat["time"], mat["disp_y"][:, idx])
        mat_z = np.interp(common_t, mat["time"], mat["disp_z"][:, idx])
        early = common_t <= 120.0
        compare_rows.append({
            "monitor": name,
            "node": node_id,
            "common_time_end_s": t_end,
            "python_end_s": float(py["time"][-1]),
            "matlab_end_s": float(mat["time"][-1]),
            "python_max_abs_x_common": float(np.max(np.abs(py_x))),
            "matlab_max_abs_x_common": float(np.max(np.abs(mat_x))),
            "python_max_abs_z_common": float(np.max(np.abs(py_z))),
            "matlab_max_abs_z_common": float(np.max(np.abs(mat_z))),
            "rms_diff_x_common": float(np.sqrt(np.mean((py_x - mat_x) ** 2))),
            "rms_diff_z_common": float(np.sqrt(np.mean((py_z - mat_z) ** 2))),
            "rms_diff_x_0_120s": float(np.sqrt(np.mean((py_x[early] - mat_x[early]) ** 2))),
            "rms_diff_z_0_120s": float(np.sqrt(np.mean((py_z[early] - mat_z[early]) ** 2))),
        })
    write_csv(POST_DIR / "python_matlab_three_point_comparison.csv", compare_rows, list(compare_rows[0].keys()))
    write_validation_report(compare_rows, py, mat)
    (POST_DIR / "validation_manifest.json").write_text(json.dumps({
        "validation_root": str(VALIDATION_ROOT),
        "python_output": str(PY_DIR),
        "matlab_output": str(MAT_DIR),
        "comparison_output": str(POST_DIR),
        "monitors": MONITORS,
    }, indent=2), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prepare", action="store_true")
    parser.add_argument("--run-python", action="store_true")
    parser.add_argument("--run-matlab", action="store_true")
    parser.add_argument("--postprocess", action="store_true")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--matlab-exe", default=r"D:\Matlab R2024b\bin\matlab.exe")
    args = parser.parse_args()

    if args.all or args.prepare:
        prepare_python_config()
        write_matlab_runner()
    if args.all or args.run_python:
        run_python_case()
    if args.all or args.run_matlab:
        run_matlab_case(args.matlab_exe)
    if args.all or args.postprocess:
        postprocess()


if __name__ == "__main__":
    main()
