from __future__ import annotations

import argparse
import csv
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from cable_analyser.analysis import CableAnalysis
from cable_analyser.config_loader import dump_config, load_config
from cable_analyser.geometry import CableGeometry


VALIDATION_ROOT = ROOT / "output" / "workflow_validation" / "broken_line_minimal_3node"
PY_DIR = VALIDATION_ROOT / "python"
MAT_DIR = VALIDATION_ROOT / "matlab"
MAT_WORK = MAT_DIR / "workspace"
POST_DIR = VALIDATION_ROOT / "comparison"
CASE_CONFIG = VALIDATION_ROOT / "validation_config_python.yaml"
N_NODES = 3
MONITOR_NODE = 2


def as_posix(path: Path) -> str:
    return str(path.resolve()).replace("\\", "/")


def prepare_python_config(npt: int = 4096) -> Path:
    cfg = load_config(ROOT / "config" / "smoke_config.yaml")
    cfg["time_history"]["npt"] = npt
    cfg["time_history"]["folder_1"] = ["FORCE_3"]
    cfg["time_history"]["folder_2"] = ["Test1"]
    cfg.setdefault("wind_generation", {})["enabled"] = False
    cfg["paths"]["output_dir"] = as_posix(PY_DIR)
    cfg["paths"]["save_prefix"] = "PY_BROKEN_LINE_MINIMAL"
    cfg["paths"]["forces_dir"] = as_posix(ROOT / "data" / "forces")
    cfg["paths"]["wind_dir"] = as_posix(ROOT / "data" / "forces" / "FORCE_3" / "Test1")
    cfg["paths"]["time_file"] = as_posix(ROOT / "data" / "aero_coeffs" / "time.txt")
    cfg["paths"]["tcl_procedures_dir"] = as_posix(ROOT / "tcl_procedures")
    cfg["solver"]["opensees_path"] = as_posix(Path(cfg["solver"]["opensees_path"]))
    cfg["solver"]["input_tcl"] = as_posix(PY_DIR / "Input.tcl")
    cfg["solver"]["work_dir"] = as_posix(ROOT)
    cfg["display"]["plotter"] = False
    cfg["display"]["modal_plotter"] = False
    cfg["display"]["realtime_monitor"] = False
    CASE_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    dump_config(cfg, CASE_CONFIG)
    return CASE_CONFIG


def write_matlab_runner(npt: int = 4096) -> None:
    MAT_WORK.mkdir(parents=True, exist_ok=True)
    (MAT_WORK / "Output").mkdir(exist_ok=True)
    (MAT_WORK / "tcl_procedures").mkdir(exist_ok=True)
    (MAT_WORK / "data" / "aero_coeffs").mkdir(parents=True, exist_ok=True)

    for name in ["PROCEDURE_OLD.tcl", "PROCEDURE_Raf_6dof.tcl"]:
        shutil.copy2(ROOT / "TIMUR4" / name, MAT_WORK / name)
    for name in ["readColumnFromFile.tcl", "interpolate.tcl", "Wind_velocity_reader.tcl", "Damping_shifter.tcl", "dynamic2.tcl"]:
        shutil.copy2(ROOT / "tcl_procedures" / name, MAT_WORK / "tcl_procedures" / name)
    for name in ["C_D_data.txt", "C_L_data2.txt", "dC_L.txt", "time.txt"]:
        shutil.copy2(ROOT / "data" / "aero_coeffs" / name, MAT_WORK / "data" / "aero_coeffs" / name)
    shutil.copy2(ROOT / "TIMUR4" / "MODAL.m", MAT_WORK / "MODAL.m")

    run_m = f"""%% Minimal broken-line validation runner generated by tools/build_broken_line_minimal_validation.py
clear all; clc;
cd('{as_posix(MAT_WORK)}');
g = 9.80665;
Plotter = 0;
Modal_plotter = 0;
Geometry = 3;
L = 2.0;
Sag = 1.0;
Discretisation = 1.0;
Dia = 0.02862;
Area = pi * Dia^2 / 4;
In = pi * Dia^4 / 64;
Io = 2 * In;
ro2 = Io/Area;
ro = 3480;
self_weight = Area * ro * g;
E = 82000000000;
G = 4265000000;
ANALYSIS_TYPE = 'TH';
FIBER_SECTION = 1;
TH_path = '{as_posix(ROOT / "data" / "forces" / "FORCE_3" / "Test1")}';
wind_time_file_validation = '{as_posix(ROOT / "data" / "aero_coeffs" / "time.txt")}';
wind_data_dir_validation = '{as_posix(ROOT / "data" / "forces" / "FORCE_3" / "Test1")}';
DT = 0.05;
NPt = {npt};
Duration = NPt * DT;
Damping_model = 'Rayleigh';
Modes_to_consider_for_damping = 10;
xi = 0.01;
Pretention_load = 0.0;
Multiplier_vertical_load = 1.242584042;
Multiplier_mass = 1.242584042;
Numbers_of_step_gravity_analysis = 10;
Tollerance = 1e-3;
Number_of_modes_to_consider = 2;

x = 0:Discretisation:L;
y = zeros(size(x));
x_mid = L / 2;
z = zeros(size(x));
for i = 1:length(x)
    if x(i) <= x_mid
        z(i) = -Sag * x(i) / x_mid;
    else
        z(i) = -Sag * (L - x(i)) / x_mid;
    end
end
angle = zeros(length(x)-1,1);
for i=1:length(x)-1
    angle(i) = atan((z(i+1)-z(i))/(x(i+1)-x(i)));
end

MODAL
TH_Constant_minimal_validation
save('{as_posix(MAT_DIR / "matlab_workspace_variables.mat")}', 'x', 'y', 'z', 'angle', 'DX', 'MN', 'MNT', 'f1');
"""
    (MAT_WORK / "run_matlab_minimal_validation.m").write_text(run_m, encoding="utf-8")

    th = (ROOT / "TIMUR4" / "TH_Constant.m").read_text(encoding="utf-8", errors="ignore")
    th = th.replace("fprintf(fid,'source Wind_velocity_reader.tcl\\n');", "\n".join([
        "fprintf(fid,'set wind_time_file \"{0}\"\\n');".format(as_posix(ROOT / "data" / "aero_coeffs" / "time.txt")),
        "fprintf(fid,'set wind_data_dir \"{0}\"\\n');".format(as_posix(ROOT / "data" / "forces" / "FORCE_3" / "Test1")),
        "fprintf(fid,'source tcl_procedures/Wind_velocity_reader.tcl\\n');",
    ]))
    th = th.replace("fprintf(fid,'source Damping_shifter.tcl\\n');", "fprintf(fid,'source tcl_procedures/Damping_shifter.tcl\\n');")
    th = th.replace("fprintf(fid,'source dynamic2.tcl\\n');", "fprintf(fid,'source tcl_procedures/dynamic2.tcl\\n');")
    th = th.replace(
        "fprintf(fid,'recorder Node -file Output/Dynamic.out -nodeRange %u %u -dof 1 2 3 disp; \\n',1, length(DX));",
        "\n".join([
            "fprintf(fid,'recorder Node -file Output/Dynamic.out -time -nodeRange %u %u -dof 1 2 3 disp; \\n',1, length(DX));",
            "fprintf(fid,'recorder Node -file Output/Velocity.out -time -nodeRange %u %u -dof 1 2 3 vel; \\n',1, length(DX));",
            "fprintf(fid,'recorder Node -file Output/Accel.out -time -nodeRange %u %u -dof 1 2 3 accel; \\n',1, length(DX));",
        ]),
    )
    th = th.replace(
        "fprintf(fid,'recorder Node -file Output/Reaction.out -node 1 -dof 1 2 3 reaction; \\n');",
        "fprintf(fid,'recorder Node -file Output/Reaction.out -time -node 1 -dof 1 2 3 reaction; \\n');",
    )
    th = th.replace(
        "fprintf(fid,'set omegaN %f\\n',2*pi*f1);",
        "fprintf(fid,'set omegaN %f\\n',2*pi*f1);\nfprintf(fid,'set xi_structural %f\\n',xi);",
        1,
    )
    th = th.replace("! \"D:\\Pyprogramme\\OpenSees3.8.0\\bin\\OpenSees.exe\" input.tcl", "! \"D:\\Pyprogramme\\OpenSees3.8.0\\bin\\OpenSees.exe\" Input.tcl")
    (MAT_WORK / "TH_Constant_minimal_validation.m").write_text(th, encoding="utf-8")


def run_python_case() -> None:
    PY_DIR.mkdir(parents=True, exist_ok=True)
    cfg_path = prepare_python_config()
    CableAnalysis(str(cfg_path)).run()


def run_matlab_case(matlab_exe: str) -> None:
    write_matlab_runner()
    cmd = [matlab_exe, "-batch", f"run('{as_posix(MAT_WORK / 'run_matlab_minimal_validation.m')}')"]
    result = subprocess.run(cmd, cwd=MAT_WORK, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"MATLAB minimal validation failed with exit code {result.returncode}")


def load_matrix(path: Path) -> np.ndarray | None:
    if not path.exists() or path.stat().st_size == 0:
        return None
    data = np.loadtxt(path)
    if data.ndim == 1:
        data = data[np.newaxis, :]
    return data


def split_node_record(data: np.ndarray, n_nodes: int) -> tuple[np.ndarray, np.ndarray]:
    if data.shape[1] == 3 * n_nodes + 1:
        return data[:, 0], data[:, 1:]
    return np.arange(data.shape[0]) * 0.05, data


def export_records(source: str, raw_dir: Path, out_dir: Path) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    dyn_raw = load_matrix(raw_dir / "Dynamic.out")
    if dyn_raw is None:
        raise FileNotFoundError(raw_dir / "Dynamic.out")
    time, dyn = split_node_record(dyn_raw, N_NODES)
    n = len(time)

    records: dict[str, Any] = {
        "source": source,
        "time": time,
        "disp": dyn.reshape(n, N_NODES, 3),
        "velocity": None,
        "accel": None,
        "reaction": None,
        "damping": None,
    }

    for stem, key in [("Velocity.out", "velocity"), ("Accel.out", "accel")]:
        raw = load_matrix(raw_dir / stem)
        if raw is not None:
            _, values = split_node_record(raw, N_NODES)
            records[key] = values.reshape(values.shape[0], N_NODES, 3)

    reaction_raw = load_matrix(raw_dir / "Reaction.out")
    if reaction_raw is not None:
        records["reaction"] = reaction_raw[:, -3:]

    damping_raw = load_matrix(raw_dir / "damping_change_log.txt")
    if damping_raw is not None:
        records["damping"] = damping_raw

    fields = ["time_s"]
    for node in range(1, N_NODES + 1):
        for comp in ["x", "y", "z"]:
            fields.append(f"node{node}_disp_{comp}_m")
    rows = []
    for i, t in enumerate(time):
        row = {"time_s": float(t)}
        for node in range(N_NODES):
            for j, comp in enumerate(["x", "y", "z"]):
                row[f"node{node+1}_disp_{comp}_m"] = float(records["disp"][i, node, j])
        rows.append(row)
    write_csv(out_dir / "all_node_displacement.csv", rows, fields)

    for key, filename, unit in [
        ("velocity", "all_node_velocity.csv", "mps"),
        ("accel", "all_node_acceleration.csv", "mps2"),
    ]:
        arr = records[key]
        if arr is None:
            continue
        fields = ["time_s"]
        for node in range(1, N_NODES + 1):
            for comp in ["x", "y", "z"]:
                fields.append(f"node{node}_{key}_{comp}_{unit}")
        rows = []
        for i, t in enumerate(time[: arr.shape[0]]):
            row = {"time_s": float(t)}
            for node in range(N_NODES):
                for j, comp in enumerate(["x", "y", "z"]):
                    row[f"node{node+1}_{key}_{comp}_{unit}"] = float(arr[i, node, j])
            rows.append(row)
        write_csv(out_dir / filename, rows, fields)

    if records["reaction"] is not None:
        write_csv(
            out_dir / "support_reaction_node1.csv",
            [{"time_s": float(time[i]), "Rx_N": float(v[0]), "Ry_N": float(v[1]), "Rz_N": float(v[2])} for i, v in enumerate(records["reaction"][: len(time)])],
            ["time_s", "Rx_N", "Ry_N", "Rz_N"],
        )
    if records["damping"] is not None:
        fields = ["time_s", "element", "previous_xi", "xi_total"]
        rows = []
        for row in records["damping"]:
            rows.append({field: float(row[i]) for i, field in enumerate(fields[: min(len(fields), len(row))])})
        write_csv(out_dir / "damping_change_log.csv", rows, fields[: records["damping"].shape[1]])

    summary = {
        "source": source,
        "rows_dynamic": int(n),
        "time_start": float(time[0]),
        "time_end": float(time[-1]),
        "has_velocity": records["velocity"] is not None,
        "has_accel": records["accel"] is not None,
        "has_damping": records["damping"] is not None,
        "middle_node_max_abs_disp": {
            "x": float(np.max(np.abs(records["disp"][:, MONITOR_NODE - 1, 0]))),
            "y": float(np.max(np.abs(records["disp"][:, MONITOR_NODE - 1, 1]))),
            "z": float(np.max(np.abs(records["disp"][:, MONITOR_NODE - 1, 2]))),
        },
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    records["summary"] = summary
    return records


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def plot_center_response(path: Path, py: dict[str, Any], mat: dict[str, Any], key: str, ylabel: str) -> None:
    py_arr = py[key]
    mat_arr = mat[key]
    if py_arr is None or mat_arr is None:
        return
    fig, axes = plt.subplots(2, 2, figsize=(13.0, 8.0), dpi=170)
    axes = axes.ravel()
    comps = [("x", 0), ("y", 1), ("z", 2)]
    for comp, idx in comps:
        axes[0].plot(py["time"][: py_arr.shape[0]], py_arr[:, MONITOR_NODE - 1, idx], lw=1.0, label=f"Python {comp}")
        axes[0].plot(mat["time"][: mat_arr.shape[0]], mat_arr[:, MONITOR_NODE - 1, idx], lw=0.85, ls="--", label=f"MATLAB {comp}")
    axes[0].set_title("Middle node: x/y/z")
    axes[0].legend(fontsize=7, ncol=2)
    for ax, (comp, idx) in zip(axes[1:], comps):
        ax.plot(py["time"][: py_arr.shape[0]], py_arr[:, MONITOR_NODE - 1, idx], lw=1.05, label="Python")
        ax.plot(mat["time"][: mat_arr.shape[0]], mat_arr[:, MONITOR_NODE - 1, idx], lw=0.9, ls="--", label="MATLAB")
        ax.set_title(f"Middle node {comp}")
        ax.legend(fontsize=8)
    for ax in axes:
        ax.grid(True, color="#D8DEE8", lw=0.6)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(ylabel)
    fig.suptitle(f"Broken-line 3-node minimal model: {key}", fontsize=14, weight="bold")
    fig.tight_layout(rect=[0, 0, 1, 0.95])
    fig.savefig(path)
    plt.close(fig)


def plot_xz(path: Path, records: dict[str, Any], title: str) -> None:
    disp = records["disp"]
    time = records["time"]
    idx = MONITOR_NODE - 1
    fig, ax = plt.subplots(figsize=(7.2, 6.0), dpi=170, layout="constrained")
    sc = ax.scatter(disp[:, idx, 0], disp[:, idx, 2], c=time, s=5, cmap="viridis", alpha=0.85)
    ax.plot(disp[:, idx, 0], disp[:, idx, 2], color="#1E252D", lw=0.35, alpha=0.45)
    ax.set_title(title)
    ax.set_xlabel("x horizontal disp (m)")
    ax.set_ylabel("z vertical disp (m)")
    ax.grid(True, color="#D8DEE8", lw=0.6)
    ax.axis("equal")
    fig.colorbar(sc, ax=ax, label="Time (s)")
    fig.savefig(path)
    plt.close(fig)


def compare_records(py: dict[str, Any], mat: dict[str, Any]) -> list[dict[str, Any]]:
    t_end = min(float(py["time"][-1]), float(mat["time"][-1]))
    t_start = max(float(py["time"][0]), float(mat["time"][0]))
    common_t = np.arange(t_start, t_end + 1e-9, 0.05)
    rows = []
    units = {"disp": "m", "velocity": "mps", "accel": "mps2"}
    for key in ["disp", "velocity", "accel"]:
        if py[key] is None or mat[key] is None:
            continue
        for node in range(N_NODES):
            for comp, idx in [("x", 0), ("y", 1), ("z", 2)]:
                py_v = np.interp(common_t, py["time"][: py[key].shape[0]], py[key][:, node, idx])
                mat_v = np.interp(common_t, mat["time"][: mat[key].shape[0]], mat[key][:, node, idx])
                rows.append({
                    "record": key,
                    "location": f"node_{node + 1}",
                    "component": comp,
                    "unit": units[key],
                    "common_time_end_s": t_end,
                    "python_max_abs": float(np.max(np.abs(py_v))),
                    "matlab_max_abs": float(np.max(np.abs(mat_v))),
                    "rms_diff": float(np.sqrt(np.mean((py_v - mat_v) ** 2))),
                    "max_abs_diff": float(np.max(np.abs(py_v - mat_v))),
                })
    if py["reaction"] is not None and mat["reaction"] is not None:
        n = min(py["reaction"].shape[0], mat["reaction"].shape[0], len(common_t))
        for comp, idx in [("Rx", 0), ("Ry", 1), ("Rz", 2)]:
            py_v = py["reaction"][:n, idx]
            mat_v = mat["reaction"][:n, idx]
            rows.append({
                "record": "reaction",
                "location": "support_node_1",
                "component": comp,
                "unit": "N",
                "common_time_end_s": float(common_t[n - 1]) if n else t_end,
                "python_max_abs": float(np.max(np.abs(py_v))),
                "matlab_max_abs": float(np.max(np.abs(mat_v))),
                "rms_diff": float(np.sqrt(np.mean((py_v - mat_v) ** 2))),
                "max_abs_diff": float(np.max(np.abs(py_v - mat_v))),
            })
    if py["damping"] is not None and mat["damping"] is not None:
        n = min(py["damping"].shape[0], mat["damping"].shape[0])
        for name, idx in [("element", 1), ("previous_xi", 2), ("xi_total", 3)]:
            if idx >= py["damping"].shape[1] or idx >= mat["damping"].shape[1]:
                continue
            py_v = py["damping"][:n, idx]
            mat_v = mat["damping"][:n, idx]
            rows.append({
                "record": "damping_log",
                "location": "all_logged_elements",
                "component": name,
                "unit": "-",
                "common_time_end_s": float(min(py["damping"][n - 1, 0], mat["damping"][n - 1, 0])) if n else t_end,
                "python_max_abs": float(np.max(np.abs(py_v))),
                "matlab_max_abs": float(np.max(np.abs(mat_v))),
                "rms_diff": float(np.sqrt(np.mean((py_v - mat_v) ** 2))),
                "max_abs_diff": float(np.max(np.abs(py_v - mat_v))),
            })
    return rows


def write_report(compare_rows: list[dict[str, Any]], py: dict[str, Any], mat: dict[str, Any]) -> None:
    center_rows = [r for r in compare_rows if r["record"] == "disp" and r["location"] == f"node_{MONITOR_NODE}"]
    exact_rows = [r for r in compare_rows if r["max_abs_diff"] == 0.0]
    lines = [
        "# Broken-line minimal 3-node MATLAB-Python validation",
        "",
        "## Purpose",
        "",
        "This is a minimal workflow check using the broken-line geometry: three nodes, two straight elements, fixed end translations, and only the middle node free to move dynamically.",
        "",
        "## Matched case",
        "",
        "- Geometry type: 3, broken-line V shape.",
        "- L = 2.0 m, Sag = 1.0 m, discretisation = 1.0 m.",
        "- Dynamic input: `data/forces/FORCE_3/Test1`.",
        "- npt = 4096, dt = 0.05 s.",
        "- Primary monitor: Node 2, the middle/free node.",
        "",
        "## Run completion",
        "",
        f"- Python: {py['summary']['rows_dynamic']} rows, {py['summary']['time_start']:.3f}-{py['summary']['time_end']:.3f} s.",
        f"- MATLAB: {mat['summary']['rows_dynamic']} rows, {mat['summary']['time_start']:.3f}-{mat['summary']['time_end']:.3f} s.",
        "",
        "## Middle-node displacement comparison",
        "",
        "| component | Python max abs (m) | MATLAB max abs (m) | RMS diff (m) | max abs diff (m) |",
        "|---|---:|---:|---:|---:|",
    ]
    for row in center_rows:
        lines.append(
            f"| {row['component']} | {row['python_max_abs']:.8g} | {row['matlab_max_abs']:.8g} | "
            f"{row['rms_diff']:.8g} | {row['max_abs_diff']:.8g} |"
        )
    lines.extend([
        "",
        "## All-record comparison status",
        "",
        f"- Compared rows in the unified error table: {len(compare_rows)}.",
        f"- Exactly matching rows: {len(exact_rows)}.",
        "- Records covered: displacement, velocity, acceleration, support reaction, and aerodynamic damping log.",
        "",
        "",
        "## Output package",
        "",
        f"- Python records and plots: `{PY_DIR / 'minimal_outputs'}`",
        f"- MATLAB records and plots: `{MAT_DIR / 'minimal_outputs'}`",
        f"- Comparison CSV: `{POST_DIR / 'python_matlab_minimal_comparison.csv'}`",
        "",
        "The package includes all-node displacement, velocity, acceleration, support reaction, damping-log CSV exports where available, four-panel middle-node comparison plots, and x-z trajectory plots.",
        "",
    ])
    (POST_DIR / "broken_line_minimal_validation_report.md").write_text("\n".join(lines), encoding="utf-8")


def postprocess() -> None:
    POST_DIR.mkdir(parents=True, exist_ok=True)
    py = export_records("python", PY_DIR, PY_DIR / "minimal_outputs")
    mat = export_records("matlab", MAT_WORK / "Output", MAT_DIR / "minimal_outputs")
    compare_rows = compare_records(py, mat)
    write_csv(POST_DIR / "python_matlab_minimal_comparison.csv", compare_rows, list(compare_rows[0].keys()))
    write_csv(POST_DIR / "python_matlab_all_record_comparison.csv", compare_rows, list(compare_rows[0].keys()))
    plot_center_response(POST_DIR / "middle_node_displacement_comparison.png", py, mat, "disp", "displacement (m)")
    plot_center_response(POST_DIR / "middle_node_velocity_comparison.png", py, mat, "velocity", "velocity (m/s)")
    plot_center_response(POST_DIR / "middle_node_acceleration_comparison.png", py, mat, "accel", "acceleration (m/s^2)")
    plot_xz(PY_DIR / "minimal_outputs" / "middle_node_xz_trajectory.png", py, "Python: middle-node x-z trajectory")
    plot_xz(MAT_DIR / "minimal_outputs" / "middle_node_xz_trajectory.png", mat, "MATLAB: middle-node x-z trajectory")
    write_report(compare_rows, py, mat)
    (POST_DIR / "validation_manifest.json").write_text(json.dumps({
        "validation_root": str(VALIDATION_ROOT),
        "python_output": str(PY_DIR),
        "matlab_output": str(MAT_DIR),
        "comparison_output": str(POST_DIR),
        "model": "broken-line minimal 3-node",
        "monitor_node": MONITOR_NODE,
    }, indent=2), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prepare", action="store_true")
    parser.add_argument("--run-python", action="store_true")
    parser.add_argument("--run-matlab", action="store_true")
    parser.add_argument("--postprocess", action="store_true")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--npt", type=int, default=4096)
    parser.add_argument("--matlab-exe", default=r"D:\Matlab R2024b\bin\matlab.exe")
    args = parser.parse_args()

    if args.all or args.prepare:
        prepare_python_config(args.npt)
        write_matlab_runner(args.npt)
    if args.all or args.run_python:
        run_python_case()
    if args.all or args.run_matlab:
        run_matlab_case(args.matlab_exe)
    if args.all or args.postprocess:
        postprocess()


if __name__ == "__main__":
    main()
