from __future__ import annotations

import csv
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "reports" / "meeting_2026_06_10"
TCL_PKG = OUT / "model_tcl_package"


TCL_GROUPS = {
    "01_fixed_shared_tcl": [
        ROOT / "tcl_procedures" / "readColumnFromFile.tcl",
        ROOT / "tcl_procedures" / "interpolate.tcl",
        ROOT / "tcl_procedures" / "Wind_velocity_reader.tcl",
        ROOT / "tcl_procedures" / "Damping_shifter.tcl",
        ROOT / "tcl_procedures" / "dynamic2.tcl",
        ROOT / "tcl_procedures" / "PROCEDURE_OLD.tcl",
        ROOT / "tcl_procedures" / "PROCEDURE_Raf_6dof.tcl",
    ],
    "02_python_generated_catenary_validation": [
        ROOT / "output" / "workflow_validation" / "matlab_python_force3_baseline" / "python" / "Input.tcl",
        ROOT / "inputs_aerodynamic_damping.tcl",
    ],
    "03_matlab_generated_catenary_validation": [
        ROOT / "output" / "workflow_validation" / "matlab_python_force3_baseline" / "matlab" / "workspace" / "Input.tcl",
        ROOT / "output" / "workflow_validation" / "matlab_python_force3_baseline" / "matlab" / "workspace" / "inputs_aerodynamic_damping.tcl",
        ROOT / "output" / "workflow_validation" / "matlab_python_force3_baseline" / "matlab" / "workspace" / "TH_Constant_validation.m",
    ],
    "04_python_generated_broken_line_minimal": [
        ROOT / "output" / "workflow_validation" / "broken_line_minimal_3node" / "python" / "Input.tcl",
        ROOT / "inputs_aerodynamic_damping.tcl",
    ],
    "05_matlab_generated_broken_line_minimal": [
        ROOT / "output" / "workflow_validation" / "broken_line_minimal_3node" / "matlab" / "workspace" / "Input.tcl",
        ROOT / "output" / "workflow_validation" / "broken_line_minimal_3node" / "matlab" / "workspace" / "inputs_aerodynamic_damping.tcl",
        ROOT / "output" / "workflow_validation" / "broken_line_minimal_3node" / "matlab" / "workspace" / "TH_Constant_minimal_validation.m",
    ],
    "06_legacy_timur_reference": [
        ROOT / "TIMUR4" / "Input.tcl",
        ROOT / "TIMUR4" / "TH_Constant.m",
        ROOT / "TIMUR4" / "MODAL.m",
        ROOT / "TIMUR4" / "Damping_shifter.tcl",
        ROOT / "TIMUR4" / "dynamic2.tcl",
        ROOT / "TIMUR4" / "Wind_velocity_reader.tcl",
    ],
}


TCL_DESCRIPTIONS = {
    "Input.tcl": "OpenSees main model file generated by the driver. It defines nodes, masses, sections, elements, boundary conditions, gravity load, aerodynamic time series, recorders, damping setup, transient solver, and sources the adaptive dynamic loop.",
    "inputs_aerodynamic_damping.tcl": "Parameter bridge for aerodynamic damping: MassM, B, tributary length L, air density, structural damping, and first circular frequency omegaN.",
    "readColumnFromFile.tcl": "Utility procedure used by coefficient and time readers to load columns from text files.",
    "interpolate.tcl": "Linear interpolation utility for aerodynamic coefficients and wind velocities.",
    "Wind_velocity_reader.tcl": "Reads node wind histories and constructs per-element horizontal and vertical wind velocity arrays for the damping routine.",
    "Damping_shifter.tcl": "Adaptive aerodynamic damping routine. It computes relative wind/cable velocity, angle of attack, C_D and dC_L/dalpha, total damping xi_total, writes damping logs, and updates element Rayleigh damping factors.",
    "dynamic2.tcl": "Adaptive transient analysis loop. It advances OpenSees in time, calls registered custom functions such as adapt_damp, records convergence state, and handles substepping/convergence recovery.",
    "PROCEDURE_OLD.tcl": "Legacy modal-report procedure retained for comparison with the original MATLAB workflow.",
    "PROCEDURE_Raf_6dof.tcl": "Modal procedure used to report modal frequencies and participation masses.",
    "TH_Constant_validation.m": "MATLAB validation-copy generator for the matched catenary case.",
    "TH_Constant_minimal_validation.m": "MATLAB validation-copy generator for the three-node broken-line minimal case.",
    "TH_Constant.m": "Original legacy MATLAB time-history Tcl generator.",
    "MODAL.m": "Original legacy MATLAB static/modal Tcl generator.",
}


def copy_tcl_package() -> None:
    if TCL_PKG.exists():
        shutil.rmtree(TCL_PKG)
    TCL_PKG.mkdir(parents=True, exist_ok=True)

    manifest_rows = []
    for group, paths in TCL_GROUPS.items():
        gdir = TCL_PKG / group
        gdir.mkdir(parents=True, exist_ok=True)
        seen: dict[str, int] = {}
        for src in paths:
            if not src.exists():
                manifest_rows.append({
                    "group": group,
                    "source": str(src),
                    "copied_as": "",
                    "status": "missing",
                    "description": TCL_DESCRIPTIONS.get(src.name, ""),
                })
                continue
            name = src.name
            seen[name] = seen.get(name, 0) + 1
            out_name = name if seen[name] == 1 else f"{src.stem}_{seen[name]}{src.suffix}"
            dst = gdir / out_name
            shutil.copy2(src, dst)
            manifest_rows.append({
                "group": group,
                "source": str(src),
                "copied_as": str(dst.relative_to(TCL_PKG)),
                "status": "copied",
                "description": TCL_DESCRIPTIONS.get(src.name, ""),
            })

    with (TCL_PKG / "model_tcl_manifest.csv").open("w", newline="", encoding="utf-8-sig") as f:
        fields = ["group", "source", "copied_as", "status", "description"]
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(manifest_rows)

    index = [
        "# Model Tcl Package Index",
        "",
        "This package collects the Tcl/MATLAB model-generation artifacts used for meeting presentation.",
        "",
        "## OpenSees Tcl Calculation Flow",
        "",
        "1. Driver writes `Input.tcl` and `inputs_aerodynamic_damping.tcl`.",
        "2. `Input.tcl` starts OpenSees, defines a 3D 6-DOF model, nodes, nodal masses, section/material objects, geometric transformations, beam-column elements, and end boundary conditions.",
        "3. Static gravity analysis is run first; static displacement and element force recorders are written.",
        "4. Modal procedures `PROCEDURE_OLD.tcl` and `PROCEDURE_Raf_6dof.tcl` extract frequencies and modal participation data.",
        "5. In time-history runs, `Input.tcl` maps precomputed aerodynamic force histories into OpenSees `Path` time series and nodal load patterns.",
        "6. Dynamic recorders write displacement, velocity, acceleration, reaction, element force, realtime state, and damping logs.",
        "7. `Wind_velocity_reader.tcl` reads wind histories and creates per-element wind velocity arrays.",
        "8. `Damping_shifter.tcl` computes the current aerodynamic damping from relative velocity and Den Hartog terms, then updates element Rayleigh damping factors.",
        "9. `dynamic2.tcl` advances the transient solution, calls adaptive damping after each step, and handles convergence/substepping.",
        "",
        "## File Groups",
        "",
    ]
    for group in TCL_GROUPS:
        index.append(f"### {group}")
        for row in [r for r in manifest_rows if r["group"] == group]:
            status = row["status"]
            copied = row["copied_as"] or "(not copied)"
            desc = row["description"] or "No description recorded."
            index.append(f"- `{copied}` [{status}]: {desc}")
        index.append("")
    (TCL_PKG / "MODEL_TCL_INDEX.md").write_text("\n".join(index), encoding="utf-8")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    copy_tcl_package()
    print(json.dumps({"output": str(OUT), "tcl_package": str(TCL_PKG)}, indent=2))


if __name__ == "__main__":
    main()
